# Generated by Django 4.2.26 on 2025-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "position", "-created_at"]},
        ),
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
