# Generated by Django 4.2.26 on 2025-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_options_todo_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["position", "-created_at"]},
        ),
    ]
